Improve: postgresqlを導入
ishideyuichi/memo_app pull request #1
Opened 2020-05-01 00:43 UTC by ishideyuichi

データの保存をファイルで行っていたが、postgresqlを導入しDBで管理するよう変更。

2020-05-02 23:45 UTC, komagata requested changes

2020-05-02 23:45 UTC, komagata commented on app.rb
> +  @memo_array = Memos.new.all
こういった変数名の付け方をハンガリアン記法といいますが、rubyではなるべく避けた方がいいやり方なので、他の名前にしてみてください。

[ハンガリアン記法 メモ \- Qiita](https://qiita.com/inabe49/items/a4eedae3b7c44fe04c0d)

ruby(特にrails)だと`@memos`などの複数形を使うのが一般的です。

2020-05-02 23:45 UTC, komagata commented on app.rb
> +  @memo = Storage.new.select(params)
Memoクラスに分けている目的ですが、ファイルに保存してもDBに保存してもアプリケーション川のコード（sinatraのappのコード）には変更が入らないようにというものなので、そういう設計を考えてみると勉強になるかもしれません。

2020-05-04 12:13 UTC, ishideyuichi commented on app.rb
> +  @memo_array = Memos.new.all
なるほど、そういった記法になってしまっていたのですね、、！
[こちらのコミット(92e071f)](https://github.com/ishideyuichi/memo_app/pull/1/commits/92e071f3365bd2f068611315be78b98b0d051770)にて`@memos`という変数名に変更しました。

2020-05-04 12:21 UTC, ishideyuichi commented on app.rb
> +  @memo = Storage.new.select(params)
クラスを分けていることで、変更の際にそういったメリットが出てくるということなのですね。
[コミット(92e071f)](https://github.com/ishideyuichi/memo_app/pull/1/commits/92e071f3365bd2f068611315be78b98b0d051770)にて、アプリケーション側のコードを変更しない形になるよう、修正しました。

2020-05-04 14:32 UTC, komagata requested changes

2020-05-04 14:32 UTC, komagata commented on app.rb
> +enable :method_override
これはデフォルトでenableのはずです〜

2020-05-04 14:32 UTC, komagata commented on storage.rb
> +    @connection = PG.connect(host: 'localhost', user: 'user01', dbname: 'memo',
設定は直書きではなく、外部から設定できるようにしたいですね！

そうでないとユーザーや接続先が変わっただけでプログラムを改修しなくてはいけなくなってしまいます。

2020-05-05 09:58 UTC, ishideyuichi commented on app.rb
> +enable :method_override
失礼しました。確認ミスで記述してしまいました。
[コミット(08bb514)](https://github.com/ishideyuichi/memo_app/pull/1/commits/08bb51498611a605d7d2f1a318cab4ea1b84b030)にて修正しました。

2020-05-05 10:02 UTC, ishideyuichi commented on storage.rb
> +    @connection = PG.connect(host: 'localhost', user: 'user01', dbname: 'memo',
なるほど、そういった設定情報は直書きしてはダメなんですね、、！
[コミット(08bb514)](https://github.com/ishideyuichi/memo_app/pull/1/commits/08bb51498611a605d7d2f1a318cab4ea1b84b030)にて、環境変数を使う形に修正しました。

2020-05-05 10:20 UTC, komagata requested changes

2020-05-05 10:20 UTC, komagata commented on memos.rb
> +    id = @all == [] ? 1 : @memos[@memos.size - 1].id + 1
これだと同時アクセスがきたときにIDが重複してしまいます。
Webアプリは秒間100アクセスとかきたりするので修正したいです。

2020-05-06 03:47 UTC, ishideyuichi commented on memos.rb
> +    id = @all == [] ? 1 : @memos[@memos.size - 1].id + 1
そういったケースについて、考えられていませんでした。
[コミット(0e59a7d)](https://github.com/ishideyuichi/memo_app/pull/1/commits/0e59a7dc16517be4802fc75767a7e342f01d3044)にて、idをserial型にして、自動で採番される形に修正しました。

2020-05-06 15:51 UTC, komagata reviewed
確認しました、OKですー🙆‍♂️

これ単体では問題ありませんが、ファイルに保存する場合だとserial型は使えないのでできればぶつからないID生成を実装したかったところです。

2020-05-07 04:16 UTC, ishideyuichi commented
ご確認ありがとうございました！
ぶつからないようなID生成についても別途確認しておくようにします。

2020-05-07 04:16 UTC, merged